# coding: utf-8

"""
    Evaluations API

    API to create and evaluate custom challenges  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.submission_feedback import SubmissionFeedback  # noqa: E501
from swagger_client.rest import ApiException


class TestSubmissionFeedback(unittest.TestCase):
    """SubmissionFeedback unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmissionFeedback(self):
        """Test SubmissionFeedback"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.submission_feedback.SubmissionFeedback()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
