# coding: utf-8

"""
    Evaluations API

    API to create and evaluate custom challenges  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aicrowd_evaluations
from aicrowd_evaluations.api.graders_api import GradersApi  # noqa: E501
from aicrowd_evaluations.rest import ApiException


class TestGradersApi(unittest.TestCase):
    """GradersApi unit test stubs"""

    def setUp(self):
        self.api = aicrowd_evaluations.api.graders_api.GradersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_grader_dao(self):
        """Test case for delete_grader_dao

        """
        pass

    def test_get_grader_dao(self):
        """Test case for get_grader_dao

        """
        pass

    def test_get_grader_list_dao(self):
        """Test case for get_grader_list_dao

        """
        pass

    def test_post_grader_list_dao(self):
        """Test case for post_grader_list_dao

        """
        pass

    def test_put_grader_dao(self):
        """Test case for put_grader_dao

        """
        pass


if __name__ == '__main__':
    unittest.main()
