# coding: utf-8

"""
    AIcrowd Evaluations API

    API to create and evaluate custom challenges on AIcrowd!  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aicrowd_evaluations
from aicrowd_evaluations.models.submissions import Submissions  # noqa: E501
from aicrowd_evaluations.rest import ApiException


class TestSubmissions(unittest.TestCase):
    """Submissions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmissions(self):
        """Test Submissions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aicrowd_evaluations.models.submissions.Submissions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
