/* 
 * Evaluations API
 *
 * API to create and evaluate custom challenges
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Com.AIcrowd.Evaluations.Client;
using Com.AIcrowd.Evaluations.Api;
using Com.AIcrowd.Evaluations.Model;

namespace Com.AIcrowd.Evaluations.Test
{
    /// <summary>
    ///  Class for testing AuthApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AuthApiTests
    {
        private AuthApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AuthApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AuthApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AuthApi
            //Assert.IsInstanceOfType(typeof(AuthApi), instance, "instance is a AuthApi");
        }

        
        /// <summary>
        /// Test PostLogoutApi
        /// </summary>
        [Test]
        public void PostLogoutApiTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xFields = null;
            //var response = instance.PostLogoutApi(xFields);
            //Assert.IsInstanceOf<AuthLogout> (response, "response is AuthLogout");
        }
        
        /// <summary>
        /// Test PostUserLogin
        /// </summary>
        [Test]
        public void PostUserLoginTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Login payload = null;
            //string xFields = null;
            //var response = instance.PostUserLogin(payload, xFields);
            //Assert.IsInstanceOf<AuthResponse> (response, "response is AuthResponse");
        }
        
    }

}
