/* 
 * Evaluations API
 *
 * API to create and evaluate custom challenges
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Com.AIcrowd.Evaluations.Client;
using Com.AIcrowd.Evaluations.Api;
using Com.AIcrowd.Evaluations.Model;

namespace Com.AIcrowd.Evaluations.Test
{
    /// <summary>
    ///  Class for testing GradersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class GradersApiTests
    {
        private GradersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new GradersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GradersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' GradersApi
            //Assert.IsInstanceOfType(typeof(GradersApi), instance, "instance is a GradersApi");
        }

        
        /// <summary>
        /// Test DeleteGraderDao
        /// </summary>
        [Test]
        public void DeleteGraderDaoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? graderId = null;
            //instance.DeleteGraderDao(graderId);
            
        }
        
        /// <summary>
        /// Test GetGraderDao
        /// </summary>
        [Test]
        public void GetGraderDaoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? graderId = null;
            //string xFields = null;
            //var response = instance.GetGraderDao(graderId, xFields);
            //Assert.IsInstanceOf<Grader> (response, "response is Grader");
        }
        
        /// <summary>
        /// Test GetGraderListDao
        /// </summary>
        [Test]
        public void GetGraderListDaoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xFields = null;
            //var response = instance.GetGraderListDao(xFields);
            //Assert.IsInstanceOf<List<Grader>> (response, "response is List<Grader>");
        }
        
        /// <summary>
        /// Test PostGraderListDao
        /// </summary>
        [Test]
        public void PostGraderListDaoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Grader payload = null;
            //string xFields = null;
            //var response = instance.PostGraderListDao(payload, xFields);
            //Assert.IsInstanceOf<Grader> (response, "response is Grader");
        }
        
    }

}
