/*
 * Evaluations API
 * API to create and evaluate custom challenges
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Organisation;
import io.swagger.client.model.OrganisationQuota;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganisationsApi
 */
@Ignore
public class OrganisationsApiTest {

    private final OrganisationsApi api = new OrganisationsApi();

    
    /**
     * 
     *
     * Delete an Organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteOrganisationDaoTest() throws ApiException {
        Integer organisationId = null;
        api.deleteOrganisationDao(organisationId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get information of an organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrganisationDaoTest() throws ApiException {
        Integer organisationId = null;
        String xFields = null;
        Organisation response = api.getOrganisationDao(organisationId, xFields);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get all organisations
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrganisationListDaoTest() throws ApiException {
        String xFields = null;
        List<Organisation> response = api.getOrganisationListDao(xFields);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Create a new organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postOrganisationListDaoTest() throws ApiException {
        Organisation payload = null;
        String xFields = null;
        Organisation response = api.postOrganisationListDao(payload, xFields);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update an Organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putOrganisationDaoTest() throws ApiException {
        Integer organisationId = null;
        Organisation payload = null;
        String xFields = null;
        Organisation response = api.putOrganisationDao(organisationId, payload, xFields);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Add or subtract quota for an organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putQuotaDaoTest() throws ApiException {
        Integer organisationId = null;
        OrganisationQuota payload = null;
        api.putQuotaDao(organisationId, payload);

        // TODO: test validations
    }
    
}
