/**
 * AIcrowd Evaluations API
 * API to create and evaluate custom challenges on AIcrowd!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.25.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SubmissionLogs.h
 *
 * 
 */

#ifndef COM_AICROWD_EVALUATIONS_MODELS_SubmissionLogs_H_
#define COM_AICROWD_EVALUATIONS_MODELS_SubmissionLogs_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "Object.h"

namespace com {
namespace aicrowd {
namespace evaluations {
namespace models {

/// <summary>
/// 
/// </summary>
class  SubmissionLogs
    : public ModelBase
{
public:
    SubmissionLogs();
    virtual ~SubmissionLogs();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SubmissionLogs members

    /// <summary>
    /// Status of the operation
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Object> getData() const;
    bool dataIsSet() const;
    void unsetData();
    void setData(std::shared_ptr<Object> value);

protected:
    utility::string_t m_Status;
    bool m_StatusIsSet;
    std::shared_ptr<Object> m_Data;
    bool m_DataIsSet;
};

}
}
}
}

#endif /* COM_AICROWD_EVALUATIONS_MODELS_SubmissionLogs_H_ */
