--[[
  Evaluations API
 
  API to create and evaluate custom challenges
 
  OpenAPI spec version: 1.0.0
  
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- generic_feedback class
local generic_feedback = {}
local generic_feedback_mt = {
	__name = "generic_feedback";
	__index = generic_feedback;
}

local function cast_generic_feedback(t)
	return setmetatable(t, generic_feedback_mt)
end

local function new_generic_feedback(status, meta)
	return cast_generic_feedback({
		["status"] = status;
		["meta"] = meta;
	})
end

return {
	cast = cast_generic_feedback;
	new = new_generic_feedback;
}
