/* 
 * Evaluations API
 *
 * API to create and evaluate custom challenges
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Cluster {
  /// ID
  #[serde(rename = "id")]
  id: Option<i32>,
  /// Creation time
  #[serde(rename = "created")]
  created: Option<String>,
  /// Last updation time
  #[serde(rename = "updated")]
  updated: Option<String>,
  /// Remote address used to connect to the cluster
  #[serde(rename = "remote_address")]
  remote_address: String,
  /// Authentication needed for the cluster
  #[serde(rename = "auth_token")]
  auth_token: String,
  /// Docker registry username
  #[serde(rename = "docker_username")]
  docker_username: String,
  /// Docker registry password
  #[serde(rename = "docker_password")]
  docker_password: String,
  /// Docker registry URL. Dockerhub is used by default.
  #[serde(rename = "docker_registry")]
  docker_registry: Option<String>,
  /// Storage class to use for datasets
  #[serde(rename = "storage_class")]
  storage_class: Option<String>,
  /// Readiness of the cluster
  #[serde(rename = "status")]
  status: Option<bool>,
  /// Additional metadata
  #[serde(rename = "meta")]
  meta: Option<Value>,
  /// User ID
  #[serde(rename = "user_id")]
  user_id: Option<i32>,
  /// Organisation ID
  #[serde(rename = "organisation_id")]
  organisation_id: Option<i32>
}

impl Cluster {
  pub fn new(remote_address: String, auth_token: String, docker_username: String, docker_password: String) -> Cluster {
    Cluster {
      id: None,
      created: None,
      updated: None,
      remote_address: remote_address,
      auth_token: auth_token,
      docker_username: docker_username,
      docker_password: docker_password,
      docker_registry: None,
      storage_class: None,
      status: None,
      meta: None,
      user_id: None,
      organisation_id: None
    }
  }

  pub fn set_id(&mut self, id: i32) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: i32) -> Cluster {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&i32> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_created(&mut self, created: String) {
    self.created = Some(created);
  }

  pub fn with_created(mut self, created: String) -> Cluster {
    self.created = Some(created);
    self
  }

  pub fn created(&self) -> Option<&String> {
    self.created.as_ref()
  }

  pub fn reset_created(&mut self) {
    self.created = None;
  }

  pub fn set_updated(&mut self, updated: String) {
    self.updated = Some(updated);
  }

  pub fn with_updated(mut self, updated: String) -> Cluster {
    self.updated = Some(updated);
    self
  }

  pub fn updated(&self) -> Option<&String> {
    self.updated.as_ref()
  }

  pub fn reset_updated(&mut self) {
    self.updated = None;
  }

  pub fn set_remote_address(&mut self, remote_address: String) {
    self.remote_address = remote_address;
  }

  pub fn with_remote_address(mut self, remote_address: String) -> Cluster {
    self.remote_address = remote_address;
    self
  }

  pub fn remote_address(&self) -> &String {
    &self.remote_address
  }


  pub fn set_auth_token(&mut self, auth_token: String) {
    self.auth_token = auth_token;
  }

  pub fn with_auth_token(mut self, auth_token: String) -> Cluster {
    self.auth_token = auth_token;
    self
  }

  pub fn auth_token(&self) -> &String {
    &self.auth_token
  }


  pub fn set_docker_username(&mut self, docker_username: String) {
    self.docker_username = docker_username;
  }

  pub fn with_docker_username(mut self, docker_username: String) -> Cluster {
    self.docker_username = docker_username;
    self
  }

  pub fn docker_username(&self) -> &String {
    &self.docker_username
  }


  pub fn set_docker_password(&mut self, docker_password: String) {
    self.docker_password = docker_password;
  }

  pub fn with_docker_password(mut self, docker_password: String) -> Cluster {
    self.docker_password = docker_password;
    self
  }

  pub fn docker_password(&self) -> &String {
    &self.docker_password
  }


  pub fn set_docker_registry(&mut self, docker_registry: String) {
    self.docker_registry = Some(docker_registry);
  }

  pub fn with_docker_registry(mut self, docker_registry: String) -> Cluster {
    self.docker_registry = Some(docker_registry);
    self
  }

  pub fn docker_registry(&self) -> Option<&String> {
    self.docker_registry.as_ref()
  }

  pub fn reset_docker_registry(&mut self) {
    self.docker_registry = None;
  }

  pub fn set_storage_class(&mut self, storage_class: String) {
    self.storage_class = Some(storage_class);
  }

  pub fn with_storage_class(mut self, storage_class: String) -> Cluster {
    self.storage_class = Some(storage_class);
    self
  }

  pub fn storage_class(&self) -> Option<&String> {
    self.storage_class.as_ref()
  }

  pub fn reset_storage_class(&mut self) {
    self.storage_class = None;
  }

  pub fn set_status(&mut self, status: bool) {
    self.status = Some(status);
  }

  pub fn with_status(mut self, status: bool) -> Cluster {
    self.status = Some(status);
    self
  }

  pub fn status(&self) -> Option<&bool> {
    self.status.as_ref()
  }

  pub fn reset_status(&mut self) {
    self.status = None;
  }

  pub fn set_meta(&mut self, meta: Value) {
    self.meta = Some(meta);
  }

  pub fn with_meta(mut self, meta: Value) -> Cluster {
    self.meta = Some(meta);
    self
  }

  pub fn meta(&self) -> Option<&Value> {
    self.meta.as_ref()
  }

  pub fn reset_meta(&mut self) {
    self.meta = None;
  }

  pub fn set_user_id(&mut self, user_id: i32) {
    self.user_id = Some(user_id);
  }

  pub fn with_user_id(mut self, user_id: i32) -> Cluster {
    self.user_id = Some(user_id);
    self
  }

  pub fn user_id(&self) -> Option<&i32> {
    self.user_id.as_ref()
  }

  pub fn reset_user_id(&mut self) {
    self.user_id = None;
  }

  pub fn set_organisation_id(&mut self, organisation_id: i32) {
    self.organisation_id = Some(organisation_id);
  }

  pub fn with_organisation_id(mut self, organisation_id: i32) -> Cluster {
    self.organisation_id = Some(organisation_id);
    self
  }

  pub fn organisation_id(&self) -> Option<&i32> {
    self.organisation_id.as_ref()
  }

  pub fn reset_organisation_id(&mut self) {
    self.organisation_id = None;
  }

}



