# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AIcrowd.Evaluations.Model.Submissions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"grader_id",
    :"submission_data",
    :"status",
    :"output",
    :"additional_outputs",
    :"logs",
    :"started",
    :"ended",
    :"meta",
    :"wf_name",
    :"workflow_priority",
    :"minimal_run",
    :"user_id",
    :"organisation_id"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"created" => DateTime.t,
    :"updated" => DateTime.t,
    :"grader_id" => integer(),
    :"submission_data" => Object,
    :"status" => String.t,
    :"output" => String.t,
    :"additional_outputs" => Object,
    :"logs" => String.t,
    :"started" => DateTime.t,
    :"ended" => DateTime.t,
    :"meta" => String.t,
    :"wf_name" => String.t,
    :"workflow_priority" => integer(),
    :"minimal_run" => boolean(),
    :"user_id" => integer(),
    :"organisation_id" => integer()
  }
end

defimpl Poison.Decoder, for: AIcrowd.Evaluations.Model.Submissions do
  import AIcrowd.Evaluations.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"submission_data", :struct, AIcrowd.Evaluations.Model.Object, options)
    |> deserialize(:"additional_outputs", :struct, AIcrowd.Evaluations.Model.Object, options)
  end
end

