/*
 * Evaluations API
 *
 * API to create and evaluate custom challenges
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GraderFeedback struct {
	// Status of the grader
	Status bool `json:"status"`
	// Serialized YAML workflow spec
	WorkflowSpec string `json:"workflow_spec"`
}
