/* 
 * Evaluations API
 *
 * API to create and evaluate custom challenges
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.AIcrowd.Evaluations.Api;
using Com.AIcrowd.Evaluations.Model;
using Com.AIcrowd.Evaluations.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.AIcrowd.Evaluations.Test
{
    /// <summary>
    ///  Class for testing SubmissionFeedback
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmissionFeedbackTests
    {
        // TODO uncomment below to declare an instance variable for SubmissionFeedback
        //private SubmissionFeedback instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmissionFeedback
            //instance = new SubmissionFeedback();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmissionFeedback
        /// </summary>
        [Test]
        public void SubmissionFeedbackInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmissionFeedback
            //Assert.IsInstanceOfType<SubmissionFeedback> (instance, "variable 'instance' is a SubmissionFeedback");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Test]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [Test]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }

    }

}
