/* 
 * AIcrowd Evaluations API
 *
 * API to create and evaluate custom challenges on AIcrowd!
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.AIcrowd.Evaluations.Api;
using Com.AIcrowd.Evaluations.Model;
using Com.AIcrowd.Evaluations.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.AIcrowd.Evaluations.Test
{
    /// <summary>
    ///  Class for testing SubmissionLogs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmissionLogsTests
    {
        // TODO uncomment below to declare an instance variable for SubmissionLogs
        //private SubmissionLogs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmissionLogs
            //instance = new SubmissionLogs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmissionLogs
        /// </summary>
        [Test]
        public void SubmissionLogsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmissionLogs
            //Assert.IsInstanceOfType<SubmissionLogs> (instance, "variable 'instance' is a SubmissionLogs");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
