/**
 * AIcrowd Evaluations API
 * API to create and evaluate custom challenges on AIcrowd!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { GenericFeedback } from '../model/genericFeedback';
import { GraderFeedback } from '../model/graderFeedback';
import { SubmissionFeedback } from '../model/submissionFeedback';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ArgoService {

    protected basePath = 'https://localhost/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Update the status of an object
     * @param modelName 
     * @param objectId 
     * @param payload 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postGenericFeedbackContract(modelName: string, objectId: number, payload: GenericFeedback, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postGenericFeedbackContract(modelName: string, objectId: number, payload: GenericFeedback, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postGenericFeedbackContract(modelName: string, objectId: number, payload: GenericFeedback, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postGenericFeedbackContract(modelName: string, objectId: number, payload: GenericFeedback, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (modelName === null || modelName === undefined) {
            throw new Error('Required parameter modelName was null or undefined when calling postGenericFeedbackContract.');
        }

        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling postGenericFeedbackContract.');
        }

        if (payload === null || payload === undefined) {
            throw new Error('Required parameter payload was null or undefined when calling postGenericFeedbackContract.');
        }

        let headers = this.defaultHeaders;

        // authentication (api_key) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["AUTHORIZATION"]) {
            headers = headers.set('AUTHORIZATION', this.configuration.apiKeys["AUTHORIZATION"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/argo/${encodeURIComponent(String(modelName))}/${encodeURIComponent(String(objectId))}`,
            payload,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Update the grader details
     * @param graderId 
     * @param payload 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postGraderFeedbackDao(graderId: number, payload: GraderFeedback, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postGraderFeedbackDao(graderId: number, payload: GraderFeedback, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postGraderFeedbackDao(graderId: number, payload: GraderFeedback, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postGraderFeedbackDao(graderId: number, payload: GraderFeedback, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (graderId === null || graderId === undefined) {
            throw new Error('Required parameter graderId was null or undefined when calling postGraderFeedbackDao.');
        }

        if (payload === null || payload === undefined) {
            throw new Error('Required parameter payload was null or undefined when calling postGraderFeedbackDao.');
        }

        let headers = this.defaultHeaders;

        // authentication (api_key) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["AUTHORIZATION"]) {
            headers = headers.set('AUTHORIZATION', this.configuration.apiKeys["AUTHORIZATION"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/argo/graders/${encodeURIComponent(String(graderId))}`,
            payload,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Update the submission details
     * @param submissionId 
     * @param payload 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postSubmissionFeedbackDao(submissionId: number, payload: SubmissionFeedback, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postSubmissionFeedbackDao(submissionId: number, payload: SubmissionFeedback, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postSubmissionFeedbackDao(submissionId: number, payload: SubmissionFeedback, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postSubmissionFeedbackDao(submissionId: number, payload: SubmissionFeedback, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (submissionId === null || submissionId === undefined) {
            throw new Error('Required parameter submissionId was null or undefined when calling postSubmissionFeedbackDao.');
        }

        if (payload === null || payload === undefined) {
            throw new Error('Required parameter payload was null or undefined when calling postSubmissionFeedbackDao.');
        }

        let headers = this.defaultHeaders;

        // authentication (api_key) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["AUTHORIZATION"]) {
            headers = headers.set('AUTHORIZATION', this.configuration.apiKeys["AUTHORIZATION"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/argo/submissions/${encodeURIComponent(String(submissionId))}`,
            payload,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
