# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule EvaluationsAPI.Model.GenericFeedback do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"meta"
  ]

  @type t :: %__MODULE__{
    :"status" => boolean(),
    :"meta" => Object
  }
end

defimpl Poison.Decoder, for: EvaluationsAPI.Model.GenericFeedback do
  import EvaluationsAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"meta", :struct, EvaluationsAPI.Model.Object, options)
  end
end

