/*
 * AIcrowd Evaluations API
 * API to create and evaluate custom challenges on AIcrowd!
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aicrowd.evaluations.api;

import com.aicrowd.evaluations.ApiException;
import com.aicrowd.evaluations.models.Organisation;
import com.aicrowd.evaluations.models.OrganisationQuota;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganisationsApi
 */
@Ignore
public class OrganisationsApiTest {

    private final OrganisationsApi api = new OrganisationsApi();

    
    /**
     * 
     *
     * Create a new organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOrganisationTest() throws ApiException {
        Organisation payload = null;
        String xFields = null;
        Organisation response = api.createOrganisation(payload, xFields);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Delete an Organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteOrganisationTest() throws ApiException {
        Integer organisationId = null;
        api.deleteOrganisation(organisationId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get details of an organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrganisationTest() throws ApiException {
        Integer organisationId = null;
        String xFields = null;
        Organisation response = api.getOrganisation(organisationId, xFields);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * List all organisations
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listOrganisationsTest() throws ApiException {
        String xFields = null;
        List<Organisation> response = api.listOrganisations(xFields);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update an Organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateOrganisationTest() throws ApiException {
        Integer organisationId = null;
        Organisation payload = null;
        String xFields = null;
        Organisation response = api.updateOrganisation(organisationId, payload, xFields);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Add or subtract quota for an organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateOrganisationQuotaTest() throws ApiException {
        Integer organisationId = null;
        OrganisationQuota payload = null;
        api.updateOrganisationQuota(organisationId, payload);

        // TODO: test validations
    }
    
}
