/*
 * AIcrowd Evaluations API
 * API to create and evaluate custom challenges on AIcrowd!
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/AIcrowdEvaluations/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/AIcrowdEvaluations/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AicrowdEvaluations);
  }
}(this, function(expect, AicrowdEvaluations) {
  'use strict';

  var instance;

  describe('AIcrowdEvaluations', function() {
    describe('GraderFeedback', function() {
      beforeEach(function() {
        instance = new AicrowdEvaluations.GraderFeedback();
      });

      it('should create an instance of GraderFeedback', function() {
        // TODO: update the code to test GraderFeedback
        expect(instance).to.be.a(AicrowdEvaluations.GraderFeedback);
      });

      it('should have the property dataset (base name: "dataset")', function() {
        // TODO: update the code to test the property dataset
        expect(instance).to.have.property('dataset');
        // expect(instance.dataset).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property notifications (base name: "notifications")', function() {
        // TODO: update the code to test the property notifications
        expect(instance).to.have.property('notifications');
        // expect(instance.notifications).to.be(expectedValueLiteral);
      });

      it('should have the property workflowSpec (base name: "workflow_spec")', function() {
        // TODO: update the code to test the property workflowSpec
        expect(instance).to.have.property('workflowSpec');
        // expect(instance.workflowSpec).to.be(expectedValueLiteral);
      });

      it('should have the property submissionTypes (base name: "submission_types")', function() {
        // TODO: update the code to test the property submissionTypes
        expect(instance).to.have.property('submissionTypes');
        // expect(instance.submissionTypes).to.be(expectedValueLiteral);
      });

    });
  });

}));
